/* eslint-disable */
"use client";

import { Sparkles, TrendingDown, TrendingUp, AlertTriangle, Lightbulb } from "lucide-react";
import type { DashboardStats } from "../types";
import { formatNumber } from "@/lib/utils";

interface AiInsightsCardProps {
    stats: DashboardStats;
}

export function AiInsightsCard({ stats }: AiInsightsCardProps) {
    if (!stats || stats.totalTargetProduce === 0 && stats.totalActualProduce === 0) {
        return null;
    }

    const { productivityPercentage, totalWorkingPeople: actualWorkers, totalSetWorkers: setWorkers } = stats;
    
    let status: "excellent" | "warning" | "critical" = "excellent";
    let title = "";
    let message = "";
    let recommendation = "";

    const overstaffedCount = actualWorkers - setWorkers;
    const isOverstaffed = overstaffedCount > 0;
    const isUnderstaffed = overstaffedCount < 0;

    if (productivityPercentage >= 100) {
        if (!isOverstaffed) {
            status = "excellent";
            title = "Highly Productive & Cost-Efficient";
            message = "Your production line is exceeding targets without overspending on labor. Income vs. labor cost is optimal.";
            recommendation = "Maintain current scheduling practices and consider rewarding top-performing lines.";
        } else {
            status = "warning";
            title = "Productive but Overstaffed (Margin Loss)";
            message = `You hit your production target, but you have ${overstaffedCount} more actual workers than scheduled. This eats into your profit margins due to higher salary costs.`;
            recommendation = "Enforce stricter RFID tap-in rules to ensure only scheduled workers are allowed on the floor.";
        }
    } else if (productivityPercentage >= 80) {
        if (!isOverstaffed) {
            status = "warning";
            title = "Slightly Underperforming";
            message = "You are close to your target and operating within your labor budget.";
            recommendation = isUnderstaffed 
                ? `You are understaffed by ${Math.abs(overstaffedCount)} workers. Try to meet your set scheduled headcount to close the productivity gap.`
                : "Check for minor machine downtimes or material delays slowing down the workers.";
        } else {
            status = "critical";
            title = "Warning: Unprofitable (Lugi)";
            message = `You are missing targets despite being OVERSTAFFED by ${overstaffedCount} workers. You are paying more in salary than the income generated by the actual produce.`;
            recommendation = "Immediately audit worker efficiency on the floor. Address loitering and ensure line leaders are managing the extra manpower.";
        }
    } else {
        if (!isOverstaffed) {
            status = "critical";
            title = "Low Productivity";
            message = "Production is significantly behind target. Labor costs are within budget, but actual income will be very low.";
            recommendation = isUnderstaffed
                ? `You are severely understaffed (${Math.abs(overstaffedCount)} missing workers). You must increase actual attendance to meet production demands.`
                : "Investigate major operational blockers such as machine breakdowns or supply chain issues.";
        } else {
            status = "critical";
            title = "Critical Warning: Severe Lugi";
            message = `Production is extremely low (${productivityPercentage}%) while labor costs are OVER BUDGET by ${overstaffedCount} extra workers. This is highly unprofitable.`;
            recommendation = "Halt current operations to recalibrate line management. Restructure the workforce and enforce strict attendance immediately.";
        }
    }

    const config = {
        excellent: {
            icon: TrendingUp,
            color: "text-emerald-600",
            bg: "bg-emerald-600/10",
            border: "border-emerald-200",
            gradient: "from-emerald-500/5 to-transparent"
        },
        warning: {
            icon: AlertTriangle,
            color: "text-amber-600",
            bg: "bg-amber-600/10",
            border: "border-amber-200",
            gradient: "from-amber-500/5 to-transparent"
        },
        critical: {
            icon: TrendingDown,
            color: "text-rose-600",
            bg: "bg-rose-600/10",
            border: "border-rose-200",
            gradient: "from-rose-500/5 to-transparent"
        }
    };

    const activeConfig = config[status];
    const Icon = activeConfig.icon;

    return (
        <div className={`rounded-xl border ${activeConfig.border} bg-gradient-to-br ${activeConfig.gradient} p-6 shadow-sm`}>
            <div className="flex items-center gap-3 mb-4">
                <div className="flex items-center justify-center p-2 rounded-lg bg-indigo-600/10">
                    <Sparkles className="h-5 w-5 text-indigo-600" />
                </div>
                <h3 className="font-bold text-lg text-indigo-950">AI Productivity Analysis</h3>
            </div>
            
            <div className="flex gap-4">
                <div className={`mt-1 shrink-0 p-3 rounded-full ${activeConfig.bg}`}>
                    <Icon className={`h-6 w-6 ${activeConfig.color}`} />
                </div>
                <div className="space-y-3">
                    <h4 className={`text-base font-bold ${activeConfig.color}`}>{title}</h4>
                    <p className="text-sm text-muted-foreground font-medium leading-relaxed">
                        {message}
                    </p>
                    <div className="flex items-start gap-2 pt-2 border-t border-border/50">
                        <Lightbulb className="h-4 w-4 text-amber-500 shrink-0 mt-0.5" />
                        <p className="text-sm text-muted-foreground font-medium">
                            <span className="text-foreground font-bold mr-1">Recommendation:</span>
                            {recommendation}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
